name-template: v$NEXT_MAJOR_VERSION
tag-template: v$NEXT_MAJOR_VERSION
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: bugfix
tag-template: - $TITLE @$AUTHOR (#$NUMBER)
template: |
  ## What’s Changed

  $CHANGES
