name: "Sync release branches"
description: "Sync release branches by creating new branch and opening PR when something get merged to releases"
branding:
  icon: git-pull-request
  color: green
inputs:
  GITHUB_TOKEN:
    description: "User token of service account."
    required: true
  SOURCE_BRANCH:
    description: "Branch to sync from where changes were merged"
    required: true
  TARGET_BRANCH:
    description: "Branch where the changes will be merged"
    required: true
  SERVICE_ACCOUNT:
    description: "Username of the service account"
    required: true
outputs:
  PULL_REQUEST_URL:
    description: "GitHub URL for either the generated pull request or the currently open one"
  PULL_REQUEST_NUMBER:
    description: "Pull request number from generated pull request or the currently open one"
runs:
  using: "node12"
  main: "dist/index.js"