name: "tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'v**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install && npm test
